### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jtianyu** [CarGuo/LearnProject#1]
What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':lottie-react-native'.
   > Could not resolve all dependencies for configuration ':lottie-react-native:_debugCompile'.
      > Could not resolve com.android.support:appcompat-v7:25.0.1.
        Required by:
            learnProject:lottie-react-native:unspecified > com.facebook.react:react-native:0.41.2
         > Could not resolve com.android.support:appcompat-v7:25.0.1.
            > Could not get resource 'https://jcenter.bintray.com/com/android/support/appcompat-v7/25.0.1/appcompat-v7-25.0.1.pom'.
               > Could not GET 'https://jcenter.bintray.com/com/android/support/appcompat-v7/25.0.1/appcompat-v7-25.0.1.pom'.
                  > peer not authenticated
      > Could not resolve com.android.support:appcompat-v7:25.0.1.
        Required by:
            learnProject:lottie-react-native:unspecified > com.airbnb.android:lottie:1.0.0
         > Could not resolve com.android.support:appcompat-v7:25.0.1.
            > Could not get resource 'https://jcenter.bintray.com/com/android/support/appcompat-v7/25.0.1/appcompat-v7-25.0.1.pom'.
               > Could not GET 'https://jcenter.bintray.com/com/android/support/appcompat-v7/25.0.1/appcompat-v7-25.0.1.pom'.
                  > peer not authenticated

**Comment by CarGuo** [comment]
npm install？

**Comment by CarGuo** [comment]
android support lib version？appcomat v7 sdk installed in Android studio？
