### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Eminem8080** [CarGuo/LearnProject#2]
已经执行了 npm install 将package.json中的类库下载到了node_moudles中并链接了原生，但是photoview中的有关fresco 的部分报错
![default](https://user-images.githubusercontent.com/9496315/28212912-4adb63c6-68d6-11e7-914a-94b16e4f6275.png)
![default](https://user-images.githubusercontent.com/9496315/28212970-8448c68a-68d6-11e7-8afc-c230766fed4c.png)
![default](https://user-images.githubusercontent.com/9496315/28212996-b2e1ba24-68d6-11e7-8c4b-1fd37842fab0.png)

**Comment by Eminem8080** [comment]
@CarGuo

**Comment by CarGuo** [comment]
你就看看photoview是不是没按照成功嘛

**Comment by zhaoziliang01** [comment]
怎么解决的啊
