### ISSUE TITLE
npm install erro 

### ISSUE THREAD

**Issue by REBOOTERS** [CarGuo/LearnProject#3]
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/C
arGuo/react-native-audio.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

"react-native-audio": "git+ssh://git@github.com/CarGuo/react-native-audio.git",

很费解，你这个链接为什么要用ssh形式，直接用正常的http 不就可以了吗？github 一般都是没有配置ssh，直接使用http 协议直接访问的呀。

**Comment by CarGuo** [comment]
这是自动生成的，你要http也可以

**Comment by hanshou101** [comment]
感谢！ install 成功了 ， 原来问题是出在这里。

**Comment by CarGuo** [comment]
对了。最近做了有一个新的rn项目，一个完整的app，有兴趣可以看看

https://github.com/CarGuo/GSYGithubAPP
