### ISSUE TITLE
npm install 报错，求指导。

### ISSUE THREAD

**Issue by ZQiang94** [CarGuo/LearnProject#5]
![image](https://user-images.githubusercontent.com/7663942/41953173-bd82a7e4-7a06-11e8-930b-34705d85d20f.png)
求指导，thx

**Comment by CarGuo** [comment]
试试packageJson改为 
    "react-native-audio": "git+https://git@github.com/CarGuo/react-native-audio.git",

**Comment by ZQiang94** [comment]
好的
